version: "3"
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  server:
    build: .
    environment:
      - PORT=5000
    expose:
      - 80
    ports:
      - 80:5000
    restart: always
volumes:
  data:
